<a href="https://colab.research.google.com/github/seungyeons2/LA2/blob/main/%EC%8B%A4%EC%8A%B50.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 라이브러리(패키지) 로드

In [ ]:
import numpy as np

def print_val(x):
  print("Type:", type(x))
  print("Shape:", x.shape)
  print("값:\n", x)
  print("")

#2.벡터, 행렬 연산, 그래프 그리기
###프린트
###rank 1 np array

In [ ]:
x = np.array([1, 2, 3])
print_val(x)

x[0] = 5
print_val(x)

Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [1 2 3]

Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [5 2 3]



###rank 2 np array

In [ ]:
y = np.array([[1,2,3], [4,5,6]])
print_val(y)

###rank 2 zeros

In [ ]:
a = np.zeros((2,2))
print_val(a)

###rank 2 ones

In [ ]:
a = np.ones((3,2))
print_val(a)

###rank 2 단위 행렬(identity matrix)


In [ ]:
a = np.eye(3,3)
print_val(a)

###랜덤 행렬(uniform: 0~1 사이 모든 값들이 나올 확률이 같음)


In [ ]:
a = np.random.random((4,4))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[0.53872058 0.66833251 0.28678885 0.73100651]
 [0.21992267 0.25776754 0.55771736 0.02705825]
 [0.93106491 0.91267285 0.07334621 0.99189492]
 [0.48592475 0.38334962 0.06699293 0.3694614 ]]



###랜덤 행렬(Gaussian: 0을 평균으로 하는 가우시안 분포를 따르는 랜덤값)

In [ ]:
a = np.random.randn(4, 4)
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (4, 4)
값:
 [[ 0.14778754  0.31844639 -0.16959579  0.20557286]
 [-0.31995809 -0.55377703  2.05185869 -0.18433004]
 [ 2.49517932 -2.8964305  -0.09633159 -0.32359589]
 [-0.06649758 -0.57560853 -1.41431699 -0.07282683]]



###np array indexing

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print_val(a)

In [ ]:
b = a[:2, 1:3]
print_val(b)

###행렬의 n번째 행 얻기

In [ ]:
row1 = a[1, :]
print_val(row1)

###행렬의 원소별 연산

In [ ]:
m1 = np.array([[1,2], [3,4]], dtype=np.float64)
m2 = np.array([[5,6], [7,8]], dtype=np.float64)

In [ ]:
#elementwise difference
print_val(m1 - m2)
print_val(np.subtract(m1, m2))

In [ ]:
#elementwise product
print_val(m1 * m2)
print_val(np.multiply(m1, m2))

In [ ]:
#elementwise division
print_val(m1 / m2)
print_val(np.divide(m1, m2))

In [ ]:
#elementwise square root
print_val(np.sqrt(m1))

###행렬 연산

In [ ]:
m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6], [7,8]])
v1 = np.array([9,10])
v2 = np.array([11,12])

print_val(m1)
print_val(m2)
print_val(v1)
print_val(v2)


###벡터-벡터 연산

In [ ]:
print_val(v1.dot(v2))
print_val(np.dot(v1, v2))

###벡터-행렬 연산

In [ ]:
print_val(m1.dot(v1)) # (2, 2) * (2, 1) -> (2, 1)
print_val(np.dot(m1, v1))

###행렬-행렬 연산

In [ ]:
print_val(m1.dot(m2))
print_val(np.dot(m1, m2))

###전치 행렬(transpose)

In [ ]:
print_val(m1)
print_val(m1.T)

###합

In [ ]:
print_val(np.sum(m1))
print_val(np.sum(m1, axis = 0))
print_val(np.sum(m1, axis = 1))


In [ ]:
m1 = np.array([[1,2,3], [4,5,6]])
print(m1)
print(m1.shape)

In [ ]:
print np.sum(m1)
print np.sum(m1, axis = 0)
print np.sum(m1, axis = 1)

###zeros-like

In [ ]:
m1 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
m2 = np.zeros_like(m1)
print_val(m1)
print_val(m2)

###Matplot library

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
#sin 커브
x = np.arange(0, 10, 0.1)
y = np.sin(x)

plt.plot(x, y)

###한 번에 두 개 그래프 그리기

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)

plt.plot(x, y_sin)
plt.plot(x, y_cos))
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('sin and cos')
plt.legend(['sin', 'cos'])

plt.show()

###Subplot

In [ ]:
plt.subplot(2, 1, 1)
plt.plot(x, y_sin)
plt.title('sin')

plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('cos')

plt.show()